AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  NotebookInstanceType:
    Description: Instance type for Notebook instance. 
    Type: String
    Default: ml.t2.medium
  ProductionInstanceType:
    Description: Instance type to launch trained production model endpoint with. 
    Type: String
    Default: ml.c4.xlarge
  SageMakerExecutionRole:
    Description: ARN of IAM role SageMaker can assume to access model artifacts and docker image for training and deployment on ML compute instances.
    Type: String
  ModelPrefix: 
    Description: Prefix to prepend to resources created for the model.
    Type: String
    Default: SageMaker-CFNDemo
  BucketName:
    Description: Name to create S3 bucket that will hold training data and model artifacts with. Must contain 'sagemaker' in name.
    Type: String
    Default: sagemaker-cfn-demo

Resources:

  CFNNotebookInstanceLifeCycleConfig:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      NotebookInstanceLifecycleConfigName: !Join ["-", ["install-gluoncv", !Ref "AWS::StackName"]]
      OnStart: 
        - Content: IyEvYmluL2Jhc2gNCg0KL2hvbWUvZWMyLXVzZXIvYW5hY29uZGEzL2VudnMvcHl0aG9uMy9iaW4vcHl0aG9uIC0tdmVyc2lvbg==
      OnCreate: 
        - Content: IyEvYmluL2Jhc2gNCg0KL2hvbWUvZWMyLXVzZXIvYW5hY29uZGEzL2VudnMvcHl0aG9uMy9iaW4vcGlwIGluc3RhbGwgZ2x1b25jdg==

  CFNNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    DependsOn: CFNNotebookInstanceLifeCycleConfig
    Properties:
      NotebookInstanceName: !Join ["-", ["CFNDemoNotebookInstance", !Ref "AWS::StackName"]]
      LifecycleConfigName: !GetAtt CFNNotebookInstanceLifeCycleConfig.NotebookInstanceLifecycleConfigName
      InstanceType: !Ref NotebookInstanceType
      RoleArn: !Ref SageMakerExecutionRole

Outputs:
  NotebookInstance:
    Description: Details about the SageMaker NotebookInstance
    Value: !Ref CFNNotebookInstance
